- name: Github to AWS CodeCommit Sync
  # You may pin to the exact commit or the version.
  # uses: tsgit18/sync-up-to-codecommit-action@f8764bf63c636c16c98d55d2ebe44fff0e37e707
  uses: tsgit18/sync-up-to-codecommit-action@v1.0.6
  with:
    # CodeCommit repository name.
    repository_name: 
    # Region of the CodeCommit repository.
    aws_region: eu-central-1
