name: sync to codecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4    
        with:
          aws-access-key-id: ${{ secrets.SYNC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SYNC_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1.0.6
        with:
          repository_name: github-sync-text
          aws_region: eu-central-1
  deploy:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@vX.X.X
        if: github.ref == 'refs/heads/main'
        with:
          aws-region: "eu-central-1"
          aws-access-key: ${{ secrets.SYNC_AWS_PIPELINE_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.SYNC_AWS_PIPELINE_SECRET_ACCESS_KEY }}
          pipeline-name: "mytestpipeline"

